server:
  port: 9000
spring:
  application:
    name: "cards"
  profiles:
    active: "prod"
  rabbitmq:
    host: "localhost"
    port: 5672
    username: "guest"
    password: "guest"
  datasource:
    url: jdbc:h2:mem:testdb
    driverClassName: org.h2.Driver
    username: sa
    password: ''
  h2:
    console:
      enabled: true
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: update
    show-sql: true

  config:
    import: "optional:configserver:http://localhost:8071/"

management:
  endpoints:
    web:
      exposure:
        include: "*" # We are telling spring boot actuator to enable and expose all management endpoints supported by Spring Boot Actuator


    ##################
    #We are mentioning {configserver} as prefix ,as it is indication to account MS or any spring boot applicaition that it
    # is going to connect with the Config Server and we are mentioning {Optional}--> we are telling account MS,it is not able
    # to connect with the configserver for whatever reason it can still continue to start MS application
    #If our properties are super important for MS then without them we can't perform any buisness logic then we can remove {optional}
